# Generated by Django 4.0.4 on 2022-05-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default=213, upload_to=''),
            preserve_default=False,
        ),
    ]
